@startuml
'https://plantuml.com/class-diagram

class Alumno {
    -String nombre
    -String apellido
    -List<Materia> materiasAprobadas
    +List<Materia> getMateriasAprobadas()
}

class Inscripcion {
    -Alumno alumno
    -List<Materia> materiasAInscribirse
    +boolean aprobada()
}

class Materia {
    -String nombre
    -List<Materia> correlativas
    +boolean cumpleCorrelativas(List<Materia>)
}

Alumno --> "*" Materia
Materia --> "*" Materia
Inscripcion o-- Alumno
Inscripcion --> "*" Materia

@enduml